module GR
  @[Link(ldflags: "-L `if [ -z $GRDIR ]; then pkg-config gr --variable=libdir ; else echo $GRDIR/lib ; fi` -lGR -Wl,-rpath,`if [ -z $GRDIR ]; then pkg-config gr --variable=libdir ; else echo $GRDIR/lib ; fi`")]
  lib LibGR
    fun initgr = gr_initgr
    fun opengks = gr_opengks
    fun closegks = gr_closegks
    fun inqdspsize = gr_inqdspsize(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Int*, x3 : LibC::Int*)
    fun openws = gr_openws(x0 : LibC::Int, x1 : LibC::Char*, x2 : LibC::Int)
    fun closews = gr_closews(x0 : LibC::Int)
    fun activatews = gr_activatews(x0 : LibC::Int)
    fun deactivatews = gr_deactivatews(x0 : LibC::Int)
    fun configurews = gr_configurews
    fun clearws = gr_clearws
    fun updatews = gr_updatews
    fun polyline = gr_polyline(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*)
    fun polymarker = gr_polymarker(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*)
    fun text = gr_text(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Char*)
    fun inqtext = gr_inqtext(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Char*, x3 : LibC::Double*, x4 : LibC::Double*)
    fun fillarea = gr_fillarea(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*)
    fun cellarray = gr_cellarray(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int, x9 : LibC::Int, x10 : LibC::Int*)
    fun nonuniformcellarray = gr_nonuniformcellarray(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Int, x3 : LibC::Int, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int*)
    fun polarcellarray = gr_polarcellarray(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int, x9 : LibC::Int, x10 : LibC::Int, x11 : LibC::Int, x12 : LibC::Int*)
    fun nonuniformpolarcellarray = gr_nonuniformpolarcellarray(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int, x9 : LibC::Int, x10 : LibC::Int*)
    fun gdp = gr_gdp(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int, x4 : LibC::Int, x5 : LibC::Int*)
    fun spline = gr_spline(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int, x4 : LibC::Int)
    fun gridit = gr_gridit(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Double*, x7 : LibC::Double*, x8 : LibC::Double*)
    fun setlinetype = gr_setlinetype(x0 : LibC::Int)
    fun inqlinetype = gr_inqlinetype(x0 : LibC::Int*)
    fun setlinewidth = gr_setlinewidth(x0 : LibC::Double)
    fun inqlinewidth = gr_inqlinewidth(x0 : LibC::Double*)
    fun setlinecolorind = gr_setlinecolorind(x0 : LibC::Int)
    fun inqlinecolorind = gr_inqlinecolorind(x0 : LibC::Int*)
    fun setmarkertype = gr_setmarkertype(x0 : LibC::Int)
    fun inqmarkertype = gr_inqmarkertype(x0 : LibC::Int*)
    fun setmarkersize = gr_setmarkersize(x0 : LibC::Double)
    fun inqmarkersize = gr_inqmarkersize(x0 : LibC::Double*)
    fun setmarkercolorind = gr_setmarkercolorind(x0 : LibC::Int)
    fun inqmarkercolorind = gr_inqmarkercolorind(x0 : LibC::Int*)
    fun settextfontprec = gr_settextfontprec(x0 : LibC::Int, x1 : LibC::Int)
    fun setcharexpan = gr_setcharexpan(x0 : LibC::Double)
    fun setcharspace = gr_setcharspace(x0 : LibC::Double)
    fun settextcolorind = gr_settextcolorind(x0 : LibC::Int)
    fun inqtextcolorind = gr_inqtextcolorind(x0 : LibC::Int*)
    fun setcharheight = gr_setcharheight(x0 : LibC::Double)
    fun inqcharheight = gr_inqcharheight(x0 : LibC::Double*)
    fun setcharup = gr_setcharup(x0 : LibC::Double, x1 : LibC::Double)
    fun settextpath = gr_settextpath(x0 : LibC::Int)
    fun settextalign = gr_settextalign(x0 : LibC::Int, x1 : LibC::Int)
    fun setfillintstyle = gr_setfillintstyle(x0 : LibC::Int)
    fun inqfillintstyle = gr_inqfillintstyle(x0 : LibC::Int*)
    fun setfillstyle = gr_setfillstyle(x0 : LibC::Int)
    fun inqfillstyle = gr_inqfillstyle(x0 : LibC::Int*)
    fun setfillcolorind = gr_setfillcolorind(x0 : LibC::Int)
    fun inqfillcolorind = gr_inqfillcolorind(x0 : LibC::Int*)
    fun setcolorrep = gr_setcolorrep(x0 : LibC::Int, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun setwindow = gr_setwindow(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun inqwindow = gr_inqwindow(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*)
    fun setviewport = gr_setviewport(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun inqviewport = gr_inqviewport(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*)
    fun selntran = gr_selntran(x0 : LibC::Int)
    fun setclip = gr_setclip(x0 : LibC::Int)
    fun setwswindow = gr_setwswindow(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun setwsviewport = gr_setwsviewport(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun createseg = gr_createseg(x0 : LibC::Int)
    fun copysegws = gr_copysegws(x0 : LibC::Int)
    fun redrawsegws = gr_redrawsegws
    fun setsegtran = gr_setsegtran(x0 : LibC::Int, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double, x6 : LibC::Double, x7 : LibC::Double)
    fun closeseg = gr_closeseg
    fun emergencyclosegks = gr_emergencyclosegks
    fun updategks = gr_updategks
    fun setspace = gr_setspace(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Int, x3 : LibC::Int) : LibC::Int
    fun inqspace = gr_inqspace(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Int*, x3 : LibC::Int*)
    fun setscale = gr_setscale(x0 : LibC::Int) : LibC::Int
    fun inqscale = gr_inqscale(x0 : LibC::Int*)
    fun textext = gr_textext(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Char*) : LibC::Int
    fun inqtextext = gr_inqtextext(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Char*, x3 : LibC::Double*, x4 : LibC::Double*)
    fun axes = gr_axes(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Double)
    fun axeslbl = gr_axeslbl(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Double, x7 : (LibC::Double, LibC::Double, LibC::Char*, LibC::Double -> Void), x8 : (LibC::Double, LibC::Double, LibC::Char*, LibC::Double -> Void))
    fun grid = gr_grid(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Int, x5 : LibC::Int)
    fun grid3d = gr_grid3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int)
    fun verrorbars = gr_verrorbars(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*)
    fun herrorbars = gr_herrorbars(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*)
    fun polyline3d = gr_polyline3d(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*)
    fun polymarker3d = gr_polymarker3d(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*)
    fun axes3d = gr_axes3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int, x9 : LibC::Double)
    fun titles3d = gr_titles3d(x0 : LibC::Char*, x1 : LibC::Char*, x2 : LibC::Char*)
    fun surface = gr_surface(x0 : LibC::Int, x1 : LibC::Int, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Int)
    fun contour = gr_contour(x0 : LibC::Int, x1 : LibC::Int, x2 : LibC::Int, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*, x6 : LibC::Double*, x7 : LibC::Int)
    fun contourf = gr_contourf(x0 : LibC::Int, x1 : LibC::Int, x2 : LibC::Int, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*, x6 : LibC::Double*, x7 : LibC::Int)
    fun tricontour = gr_tricontour(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Int, x5 : LibC::Double*)
    fun hexbin = gr_hexbin(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int) : LibC::Int
    fun setcolormap = gr_setcolormap(x0 : LibC::Int)
    fun inqcolormap = gr_inqcolormap(x0 : LibC::Int*)
    fun setcolormapfromrgb = gr_setcolormapfromrgb(n : LibC::Int, r : LibC::Double*, g : LibC::Double*, b : LibC::Double*, x : LibC::Double*)
    fun inqcolormapinds = gr_inqcolormapinds(x0 : LibC::Int*, x1 : LibC::Int*)
    fun colorbar = gr_colorbar
    fun inqcolor = gr_inqcolor(x0 : LibC::Int, x1 : LibC::Int*)
    fun inqcolorfromrgb = gr_inqcolorfromrgb(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double) : LibC::Int
    fun hsvtorgb = gr_hsvtorgb(h : LibC::Double, s : LibC::Double, v : LibC::Double, r : LibC::Double*, g : LibC::Double*, b : LibC::Double*)
    fun tick = gr_tick(x0 : LibC::Double, x1 : LibC::Double) : LibC::Double
    fun validaterange = gr_validaterange(x0 : LibC::Double, x1 : LibC::Double) : LibC::Int
    fun adjustlimits = gr_adjustlimits(x0 : LibC::Double*, x1 : LibC::Double*)
    fun adjustrange = gr_adjustrange(x0 : LibC::Double*, x1 : LibC::Double*)
    fun beginprint = gr_beginprint(x0 : LibC::Char*)
    fun beginprintext = gr_beginprintext(x0 : LibC::Char*, x1 : LibC::Char*, x2 : LibC::Char*, x3 : LibC::Char*)
    fun endprint = gr_endprint
    fun ndctowc = gr_ndctowc(x0 : LibC::Double*, x1 : LibC::Double*)
    fun wctondc = gr_wctondc(x0 : LibC::Double*, x1 : LibC::Double*)
    fun wc3towc = gr_wc3towc(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*)
    fun drawrect = gr_drawrect(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun fillrect = gr_fillrect(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun drawarc = gr_drawarc(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double)
    fun fillarc = gr_fillarc(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double)
    fun drawpath = gr_drawpath(x0 : LibC::Int, x1 : VertexT*, x2 : UInt8*, x3 : LibC::Int)

    struct VertexT
      x : LibC::Double
      y : LibC::Double
    end

    fun setarrowstyle = gr_setarrowstyle(x0 : LibC::Int)
    fun setarrowsize = gr_setarrowsize(x0 : LibC::Double)
    fun drawarrow = gr_drawarrow(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun readimage = gr_readimage(x0 : LibC::Char*, x1 : LibC::Int*, x2 : LibC::Int*, x3 : LibC::Int**) : LibC::Int
    fun drawimage = gr_drawimage(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Int, x5 : LibC::Int, x6 : LibC::Int*, x7 : LibC::Int)
    fun importgraphics = gr_importgraphics(x0 : LibC::Char*) : LibC::Int
    fun setshadow = gr_setshadow(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double)
    fun settransparency = gr_settransparency(x0 : LibC::Double)
    fun setcoordxform = gr_setcoordxform(x0 : LibC::Double[2][3])
    fun begingraphics = gr_begingraphics(x0 : LibC::Char*)
    fun endgraphics = gr_endgraphics
    fun getgraphics = gr_getgraphics : LibC::Char*
    fun drawgraphics = gr_drawgraphics(x0 : LibC::Char*) : LibC::Int
    fun mathtex = gr_mathtex(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Char*)
    fun inqmathtex = gr_inqmathtex(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Char*, x3 : LibC::Double*, x4 : LibC::Double*)
    fun beginselection = gr_beginselection(x0 : LibC::Int, x1 : LibC::Int)
    fun endselection = gr_endselection
    fun moveselection = gr_moveselection(x0 : LibC::Double, x1 : LibC::Double)
    fun resizeselection = gr_resizeselection(x0 : LibC::Int, x1 : LibC::Double, x2 : LibC::Double)
    fun inqbbox = gr_inqbbox(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*)
    fun precision = gr_precision : LibC::Double
    fun setregenflags = gr_setregenflags(x0 : LibC::Int)
    fun inqregenflags = gr_inqregenflags : LibC::Int
    fun savestate = gr_savestate
    fun restorestate = gr_restorestate
    fun selectcontext = gr_selectcontext(x0 : LibC::Int)
    fun destroycontext = gr_destroycontext(x0 : LibC::Int)
    fun uselinespec = gr_uselinespec(x0 : LibC::Char*) : LibC::Int
    fun delaunay = gr_delaunay(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int*, x4 : LibC::Int**)
    fun reducepoints = gr_reducepoints(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int, x4 : LibC::Double*, x5 : LibC::Double*)
    fun trisurface = gr_trisurface(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*)
    fun gradient = gr_gradient(x0 : LibC::Int, x1 : LibC::Int, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*, x6 : LibC::Double*)
    fun quiver = gr_quiver(x0 : LibC::Int, x1 : LibC::Int, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*, x6 : LibC::Int)
    fun interp2 = gr_interp2(nx : LibC::Int, ny : LibC::Int, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*, nxq : LibC::Int, nyq : LibC::Int, xq : LibC::Double*, yq : LibC::Double*, zq : LibC::Double*, method : LibC::Int, extrapval : LibC::Double)
    fun version = gr_version : LibC::Char*
    fun shade = gr_shade(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int, x4 : LibC::Int, x5 : LibC::Double*, x6 : LibC::Int, x7 : LibC::Int, x8 : LibC::Int*)
    fun shadepoints = gr_shadepoints(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int, x4 : LibC::Int, x5 : LibC::Int)
    fun shadelines = gr_shadelines(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Int, x4 : LibC::Int, x5 : LibC::Int)
    fun panzoom = gr_panzoom(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double*, x5 : LibC::Double*, x6 : LibC::Double*, x7 : LibC::Double*)
    fun findboundary = gr_findboundary(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double, x4 : (LibC::Double, LibC::Double -> LibC::Double), x5 : LibC::Int, x6 : LibC::Int*) : LibC::Int
    fun setresamplemethod = gr_setresamplemethod(x0 : LibC::UInt)
    fun inqresamplemethod = gr_inqresamplemethod(x0 : LibC::UInt*)
    fun path = gr_path(x0 : LibC::Int, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Char*)
    fun setborderwidth = gr_setborderwidth(x0 : LibC::Double)
    fun inqborderwidth = gr_inqborderwidth(x0 : LibC::Double*)
    fun setbordercolorind = gr_setbordercolorind(x0 : LibC::Int)
    fun inqbordercolorind = gr_inqbordercolorind(x0 : LibC::Int*)
    fun selectclipxform = gr_selectclipxform(x0 : LibC::Int)
    fun inqclipxform = gr_inqclipxform(x0 : LibC::Int*)
    fun setprojectiontype = gr_setprojectiontype(x0 : LibC::Int)
    fun inqprojectiontype = gr_inqprojectiontype(x0 : LibC::Int*)
    fun setperspectiveprojection = gr_setperspectiveprojection(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double)
    fun inqperspectiveprojection = gr_inqperspectiveprojection(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*)
    fun settransformationparameters = gr_settransformationparameters(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double, x6 : LibC::Double, x7 : LibC::Double, x8 : LibC::Double)
    fun inqtransformationparameters = gr_inqtransformationparameters(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*, x6 : LibC::Double*, x7 : LibC::Double*, x8 : LibC::Double*)
    fun setorthographicprojection = gr_setorthographicprojection(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double)
    fun inqorthographicprojection = gr_inqorthographicprojection(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*)
    fun camerainteraction = gr_camerainteraction(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun setwindow3d = gr_setwindow3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double, x4 : LibC::Double, x5 : LibC::Double)
    fun inqwindow3d = gr_inqwindow3d(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*, x3 : LibC::Double*, x4 : LibC::Double*, x5 : LibC::Double*)
    fun setscalefactors3d = gr_setscalefactors3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double)
    fun inqscalefactors3d = gr_inqscalefactors3d(x0 : LibC::Double*, x1 : LibC::Double*, x2 : LibC::Double*)
    fun setspace3d = gr_setspace3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Double)
    fun text3d = gr_text3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Char*, axis : LibC::Int)
    fun inqtext3d = gr_inqtext3d(x0 : LibC::Double, x1 : LibC::Double, x2 : LibC::Double, x3 : LibC::Char*, axis : LibC::Int, x5 : LibC::Double*, x6 : LibC::Double*)
    fun settextencoding = gr_settextencoding(x0 : LibC::Int)
    fun inqtextencoding = gr_inqtextencoding(x0 : LibC::Int*)
    fun loadfont = gr_loadfont(x0 : LibC::Char*, x1 : LibC::Int*)
    fun setcallback = gr_setcallback(x0 : (LibC::Char* -> LibC::Char*))
    fun setthreadnumber = gr_setthreadnumber(x0 : LibC::Int)
    fun setpicturesizeforvolume = gr_setpicturesizeforvolume(x0 : LibC::Int, x1 : LibC::Int)
    fun setvolumebordercalculation = gr_setvolumebordercalculation(x0 : LibC::Int)
    fun inqvolumeflags = gr_inqvolumeflags(x0 : LibC::Int*, x1 : LibC::Int*, x2 : LibC::Int*, x3 : LibC::Int*)
    fun cpubasedvolume = gr_cpubasedvolume(x0 : LibC::Int, x1 : LibC::Int, x2 : LibC::Int, x3 : LibC::Double*, x4 : LibC::Int, x5 : LibC::Double*, x6 : LibC::Double*, x7 : LibC::Double*, x8 : LibC::Double*)
  end
end
