name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Crystal ${{ matrix.crystal }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v5
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install Ubuntu packages (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          wget https://download.opensuse.org/repositories/science:/gr-framework/xUbuntu_24.04/amd64/gr_0.73.17-1_amd64.deb
          sudo apt-get install -y ./gr_0.73.17-1_amd64.deb
      - name: Set up Homebrew (macos)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew update
          brew install libgr
      - run: shards install
      - name: Run tests (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        env:
          QT_QPA_PLATFORM: offscreen
          GRDIR: /usr/gr
        run: crystal spec
      - name: Run tests (macos)
        if: ${{ matrix.os == 'macos' }}
        env:
          QT_QPA_PLATFORM: offscreen
        run: crystal spec
