on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install GR
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          wget https://download.opensuse.org/repositories/science:/gr-framework/xUbuntu_20.04/amd64/gr_0.63.1-1_amd64.deb
          sudo apt-get install -y ./gr_0.63.1-1_amd64.deb
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec