on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Update Ubuntu packages
        run: |
          : # Required before installing GR (2022-02-12)
          sudo apt update -y
          sudo apt upgrade -y
      - name: Install GR
        run: |
          wget https://download.opensuse.org/repositories/science:/gr-framework/xUbuntu_20.04/amd64/gr_0.64.0-1_amd64.deb
          sudo apt-get install -y ./gr_0.64.0-1_amd64.deb
      - name: Install shards
        run: shards install
      - name: Run tests
        env:
          QT_QPA_PLATFORM: offscreen
          GRDIR: /usr/gr
        run: crystal spec
